steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/leemet-ee/vinyl', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/leemet-ee/vinyl']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'vinyl', '--region=europe-west1', '--platform=managed', '--image=gcr.io/leemet-ee/vinyl:latest']
